
[language-server.ruff]
command = "ruff-lsp"
# config = { settings = { run = "onSave" } }

[[language]]
name = "python"
scope = "source.python"
language-servers = ["pylsp", "ruff"]

[language-server.nu-lsp]
command = "nu"
args = [ "--lsp" ]

[[language]]
name = "nu"
scope = "source.nu"
injection-regex = "nu"
file-types = ["nu"]
shebangs = ["nu"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
# language-servers = [ "nu-lsp" ]

[[grammar]]
name = "nu"
source = { git = "https://github.com/nushell/tree-sitter-nu", rev = "main" }

[[language]]
name = "gemini"
scope = "source.gmi"
file-types = ["gmi"]

[[grammar]]
name = "gemini"
source = { git = "https://git.sr.ht/~nbsp/tree-sitter-gemini", rev = "3cc5e4bdf572d5df4277fc2e54d6299bd59a54b3" }
