
[[language]]
name = "ini"
file-types = [ "ini",
  { glob = "*.desktop" },
  { glob = "*.service" },
  { glob = "viebrc" },
  { glob = "gitconfig" },
  { glob = "opencommit" },
  { glob = "qView.conf" },
  { glob = "mimeapps.list" },
  { glob = "imv/config" },
]

[[language]]
name = "bash"
file-types = [ "sh",
{ glob = "bat/**" },
{ glob = "regolith3/**" },
{ glob = "ghostty/**" },
{ glob = "sway/**" },
{ glob = "**/*.conf" },
{ glob = "kitty/*.conf" },
{ glob = "hyde/state/*" }
]

[[language]]
name = "hyprlang"
file-types = [{ glob = "hypr/**/*.conf" }]

[[language]]
name = "common-lisp"
file-types = ["lisp", { glob = "kanata/**" }]

[[language]]
name = "ron"
file-types = ["ron", { glob = "cosmic/**" }]

[[language]]
name = "jsonc"
file-types = ["jsonc", { glob = "zed/*.json" }]
