
[[language]]
name = "bash"
file-types = ["sh", { glob = "bat/**" }, { glob = "regolith3/**" }, { glob = "ghostty/**" }, { glob = "sway/**" }, { glob = "**/*.conf" }, { glob = "kitty/*.conf" }]

[[language]]
name = "hyprlang"
file-types = [{ glob = "hypr/**/*.conf" }]

[[language]]
name = "common-lisp"
file-types = ["lisp", { glob = "kanata/**" }]

[[language]]
name = "ron"
file-types = ["ron", { glob = "cosmic/**" }]

[[language]]
name = "ini"
file-types = [
{ glob = "**/*.ini" },
{ glob = "*.desktop" },
{ glob = "*.service" },
{ glob = "mimeapps.list" },
{ glob = "gitconfig" },
{ glob = "opencommit" },
{ glob = "qView.conf" },
{ glob = "imv/*" },
]
