
[[language]]
name = "bash"
file-types = ["sh", { glob = "bat/**" }, { glob = "regolith3/**" }, { glob = "ghostty/**" }, { glob = "sway/**" }]

[[language]]
name = "common-lisp"
file-types = ["lisp", { glob = "kanata/**" }]

[[language]]
name = "ron"
file-types = ["ron", { glob = "cosmic/**" }]
