# configure release bind
release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

# optional port (defaults to 4242)
port = 4242
# # optional frontend -> defaults to gtk if available
# # possible values are "cli" and "gtk"
frontend = "cli"

# define a client on the right side with host name "iridium"
[left]
# hostname
# hostname = "anthony-desktop-home"
# activate this client immediately when lan-mouse is started
activate_on_startup = false
# optional list of (known) ip addresses
ips = ["192.168.0.11", "192.168.0.110"]

# define a client on the left side with IP address 192.168.178.189
[right]
# The hostname is optional: When no hostname is specified,
# at least one ip address needs to be specified.
# hostname = "anthony-micro-home"
ips = ["192.168.0.12", "192.168.0.111"]
port = 4242
